### ISSUE TITLE
No Local Device Found

### ISSUE THREAD

**Issue by amoghjain1988** [chmoore889/esp_local_control#2]
Hello,

I am trying to get the library to work but I am having a hard time to get it to work and communicate with rainmaker API.

I have 2 errors that I have been able to print using logs
1. error found : no mDNS broadcast with mentioned Device
2. No local device found

what I have done so far to ensure connectivity:-
- device is claimed and local control is avaiable via rainmaker app
- can perform "ping deviceID.local" and recieve response on dev laptop terminal
- device ID is passed right to LocalControl Constructor
- Both the app, and device are on the same network.
- tried to debug and follow but keep getting lost!

Can you please guide and/or give some pointers where I might be going wrong?

Thanks

**Comment by chmoore889** [comment]
@amoghjain1988 Please share a minimal code example with the problem and all relevant logs for the Dart side. Also share logs from your Rainmaker device when you're trying to connect.

**Comment by amoghjain1988** [comment]
Hello, 

Thanks for such a fast response and developing the package!!

I am still debugging the issue and nearing the root cause. What I think the issue is related to certificates and https. The app works fine otherwise, and is able to detect the ip and port.

I will update in next couple days the final results.

As of now, I have attached the PDF where I track the issue, and shows
- http connection is not allowed.
- making https requires certs
- my current cert has mismatching domain/CN name.

[localcontrol_debug.pdf](https://github.com/chmoore889/esp_local_control/files/6391004/localcontrol_debug.pdf)

I dont know if you want to just close the issue, as it seems its just https, and app's as designed http functionality works!

**Comment by chmoore889** [comment]
@amoghjain1988  At least when I was working on this package, HTTPS Local Control was not supported by ESP Rainmaker and you had to use HTTP, which is why changing to HTTPS wouldn't work. HTTP isn't normally allowed by Android or iOS, so you have to enable it, which can be done with [these instructions](https://stackoverflow.com/a/65730723/13250142). I should put instructions for how to do that in the package's readme. Hopefully I remember before the next release.

**Comment by amoghjain1988** [comment]
Hello @chmoore889 

I tried what you recommended and it works quite well now! Rather flawlessly!

I have another question I was hoping you can shed some light or point me in the right direction.

Though the app works quite well with the rainmaker_example_component, I was trying to make "esp_Local_control" component work with the app as well. But I keep running to this error : "FormatException (FormatException: Unexpected character (at character 1)" as shown in the picture. 

![Screenshot from 2021-04-30 04-14-03](https://user-images.githubusercontent.com/20871880/116667874-ada79280-a96a-11eb-89bb-07e05117369e.png)

Is it because of some protocol issue? I tried googling but couldnt get much anywhere.

Compared to RainMaker's component, I had to turn off https and certs requirement in the esp_local_control example.

Here is the a picture of what I see on the esp_terminal when I try to run the app.

![Screenshot from 2021-04-30 04-14-03](https://user-images.githubusercontent.com/20871880/116668186-1262ed00-a96b-11eb-9974-91b58642a1c6.png)

Please note, the library is able to identify the device, and retrieve the IP! Issue comes when sending/reciving data, when working with esp_local_control example.

Thank you in advance!
